name: Sonar + NuGet CI
  # Este workflow puede incluir pasos para publicar paquetes nuget
env:
  DOTNET_VERSION: '8.x'                     # la versión de .NET
  SONAR_ORG: 'krcrimson'                    # Nombre de la organización de sonar cloud
  SONAR_PROJECT: 'krcrimson_apibank'        # Key ID del proyecto de sonar
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube Analisys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Instalar Scanner
        if: secrets.SONAR_TOKEN != ''
        run: dotnet tool install -g dotnet-sonarscanner
        
      - name: Debug SonarCloud Config
        if: secrets.SONAR_TOKEN != ''
        run: |
          echo "SONAR_ORG: ${{ env.SONAR_ORG }}"
          echo "SONAR_PROJECT: ${{ env.SONAR_PROJECT }}"
          echo "Token configured: ${{ secrets.SONAR_TOKEN != '' }}"
      - name: SonarCloud Begin
        working-directory: ./Bank
        if: secrets.SONAR_TOKEN != ''
        run: |
          dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.qualitygate.wait=true

      - name: Restore and Build
        working-directory: ./Bank
        run: |
          dotnet restore 
          dotnet build --configuration Release --no-restore

      - name: Run Tests
        working-directory: ./Bank
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage;Format=opencover"

      - name: SonarCloud End
        working-directory: ./Bank
        if: secrets.SONAR_TOKEN != ''
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Pack NuGet Package
        working-directory: ./Bank
        run: dotnet pack Bank.Domain/Bank.Domain.csproj --configuration Release --output ./nupkg --no-build /p:PackageVersion=1.0.${{ github.run_number }}

      - name: Configure NuGet Source
        working-directory: ./Bank
        run: dotnet nuget add source --username UPT-FAING-EPIS --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/UPT-FAING-EPIS/index.json"

      - name: Publish NuGet Package
        working-directory: ./Bank
        run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Release 1.0.${{ github.run_number }}"
          body: |
            ## Cambios en esta versión
            - Publicación automática del paquete NuGet Bank.Domain v1.0.${{ github.run_number }}
            - Análisis de calidad de código con SonarCloud
            - Ejecución de pruebas unitarias con cobertura de código
            
            **Commit:** ${{ github.sha }}
            **Run:** ${{ github.run_number }}
          files: ./Bank/nupkg/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}